// <auto-generated />
using System;
using Database.DatabaseClasses;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Database.Migrations
{
    [DbContext(typeof(DemoCentralContext))]
    partial class DemoCentralContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DataBase.DatabaseClasses.Demo", b =>
                {
                    b.Property<long>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<string>("BlobUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DatabaseVersion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte>("DemoFileWorkerStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<string>("DemoFileWorkerVersion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("DownloadUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Event")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte>("FileStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("FramesPerSecond")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Md5hash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<byte>("Quality")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("Source")
                        .HasColumnType("tinyint unsigned");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime(6)");

                    b.Property<byte>("UploadStatus")
                        .HasColumnType("tinyint unsigned");

                    b.Property<byte>("UploadType")
                        .HasColumnType("tinyint unsigned");

                    b.Property<long>("UploaderId")
                        .HasColumnType("bigint");

                    b.HasKey("MatchId");

                    b.ToTable("Demo");
                });

            modelBuilder.Entity("DataBase.DatabaseClasses.InQueueDemo", b =>
                {
                    b.Property<long>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    b.Property<bool>("DDQUEUE")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("DFWQUEUE")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("InsertDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Retries")
                        .HasColumnType("int");

                    b.Property<bool>("SOQUEUE")
                        .HasColumnType("tinyint(1)");

                    b.Property<long>("UploaderId")
                        .HasColumnType("bigint");

                    b.HasKey("MatchId");

                    b.ToTable("InQueueDemo");
                });
#pragma warning restore 612, 618
        }
    }
}
